name: Node CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.3.1
      - name: install pnpm
        run: npm i -g pnpm      
      - name: install dependencies
        run: pnpm i
      - name: validate code style
        run: pnpm lint
      - name: build and typecheck
        run: pnpm build
      - name: generate static pages
        run: pnpm generate